services:
    auth.provider.oauth.service.keycloak:
        class: ectua\keycloak\core\keycloak
        arguments:
            - @config
            - @request
        tags:
            - { name: auth.provider.oauth.service }